services:
  - name: frontend
    type: web
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://api.topgear.ph/api
    autoDeploy: true

  - name: backend
    type: web
    env: node
    buildCommand: cd cms && npm install
    startCommand: cd cms && npm run start
    envVars:
      - key: DATABASE_URI
        sync: false
      - key: PAYLOAD_SECRET
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: true

databases:
  - name: mongo
    databaseName: topgear
    ipAllowList: []
