services:
  - name: frontend
    type: web
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://api.topgear.onrender.com/api
    autoDeploy: true
    domains:
      - topgear.onrender.com

  - name: backend
    type: web
    env: node
    buildCommand: cd cms && npm install && npm run build
    startCommand: cd cms && npm run start
    envVars:
      - key: DATABASE_URI
        sync: false
      - key: PAYLOAD_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://topgear.onrender.com
    autoDeploy: true
    domains:
      - api.topgear.onrender.com

databases:
  - name: mongo
    databaseName: topgear
    ipAllowList: []
