services:
  - name: topgear-cms
    type: web
    env: node
    buildCommand: cd cms && npm install && npm run build
    startCommand: cd cms && npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PAYLOAD_SECRET
        sync: false
      - key: PAYLOAD_PUBLIC_SERVER_URL
        value: https://topgear-cms.onrender.com
    healthCheckPath: /api/healthz
    autoDeploy: true
    branch: render-deployment

  - name: topgear-frontend
    type: web
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_CMS_URL
        value: https://topgear-cms.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
    branch: render-deployment

databases:
  - name: topgear-mongodb
    databaseName: topgear-cms
    ipAllowList: []
    plan: free
